version: 0.2

phases:
  build:
    commands:
      - ./gradlew clean build
artifacts:
  files:
    - build/libs/memedatabasebot-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes