#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/memebot?user=root&useSSL=false&serverTimezone=UTC
#    password: INSERT_PASSWORD_HERE
#
#server:
#  port: 3003
#
#credentials:
#  consumer:
#    key: PUT_VALUE_HERE
#    secret: PUT_VALUE_HERE
#  access:
#    key: PUT_VALUE_HERE
#    secret: PUT_VALUE_HERE
#
#pathPrefix: /Users/Alec/Desktop/writeToFolder
#
#resilience4j:
#  circuitbreaker:
#    backends:
#      postTweet:
#        slidingWindowSize: 5
#        failureRateThreshold: 100
#        waitDurationInOpenState: 20000
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 1
#        ignoreExceptions:
#          - org.springframework.web.client.HttpClientErrorException
#  retry:
#    backends:
#      postTweet:
#        maxRetryAttempts: 5
#        retryExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#        ignoreExceptions:
#          - org.springframework.web.client.HttpClientErrorException