#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/memebot?user=root&useSSL=false&serverTimezone=UTC
#    password: INSERT_PASSWORD_HERE
#
#server:
#  port: 3003
#  servelet:
#    context-path: /api/memebot
#
#auth:
#  consumer:
#    apiKey: PUT_VALUE_HERE
#    apiSecretKey: PUT_VALUE_HERE
#  access:
#    token: PUT_VALUE_HERE
#    tokenSecret: PUT_VALUE_HERE
#
#pathPrefix: /Users/Alec/Desktop/writeToFolder