#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/memebot?user=root&useSSL=false&serverTimezone=UTC
#    password: INSERT_PASSWORD_HERE
#
#server:
#  port: 3003
#
#credentials:
#  consumer:
#    key: PUT_VALUE_HERE
#    secret: PUT_VALUE_HERE
#  access:
#    key: PUT_VALUE_HERE
#    secret: PUT_VALUE_HERE
#
#pathPrefix: /Users/Alec/Desktop/writeToFolder
