#credentials:
#  consumer:
#    key: INSERT_VALUE_HERE
#    secret: INSERT_VALUE_HERE
#  access:
#    key: INSERT_VALUE_HERE
#    secret: INSERT_VALUE_HERE
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/memebot?user=root&useSSL=false&serverTimezone=UTC
#    password: INSERT_VALUE_HERE
#
#pathPrefix: /Users/Alec/Desktop/writeToFolder
#
#defaultCheckAfterSecs: 5
#
#connectToTwitter: true